---
abstract: 'Warn when deprecated subroutines are used'
author:
  - 'Nathaniel G. Nutter <nnutter@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Deprecated
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Sub::Deprecated:
    file: lib/Sub/Deprecated.pm
    version: 0.04
requires:
  Attribute::Handlers: 0.93
  perl: 5.008005
resources:
  bugtracker: https://github.com/nnutter/Sub-Deprecated/issues
  homepage: https://github.com/nnutter/Sub-Deprecated
  repository: git://github.com/nnutter/Sub-Deprecated.git
version: 0.04
x_contributors:
  - 'Nathaniel Nutter <iam@nnutter.com>'
